### ISSUE TITLE
Working outside an application

### ISSUE THREAD

**Issue by hoppithek** [ZFrapid/zf2rapid#11]
When working on a reusable base module you currently need a dummy skeleton application somewhere to execute create commands. There should be an option to work directly on a module without the need to provide an application. I didn't look to closely, but it seems application is only needed to modify `application.config.php`.

**Comment by RalfEggert** [comment]
Good point. Need to think about this.

**Comment by RalfEggert** [comment]
Currently, you can specify the `--projectPath=` value flag for almost any command. The `projectPath` is used to find the ZF2 project to work in. Additionally you can add the `--modulePath=` value flag with defaults to `module`. In combination with the new `--no-activation` flag you could archive the creation of a module in any path:

```
$ zf2rapid create-module Shop --projectPath=/tmp --modulePath=. --no-activation
```

But that seems not be very handy. I am thinking of reworking this to make it more easier. If the `modulePath` is not available within the `projectPath` and has a leading `/` the `projectPath` could be ignored and the module activation would not processed.

```
$ zf2rapid create-module Shop --modulePath=/tmp
```

Any thoughts?

**Comment by hoppithek** [comment]
Sounds good, but since you try to keep it as simple as possible for ppl starting with ZF2 maybe an option to explicitly turn off working with a project would be  better. This would also allow for relative module paths: 

`zf2rapid create-module [--projectPath= | --no-project] [--modulePath=]`
If neither `--projectPath` nor `--no-project`is given the default project path is used, which means no change to the current behavior.

Alternatively checking if the default project path, when not set explicitly, is a valid project directory (e.g. by testing for `getcwd() . '/config/application.config.php'` might be a more intuitive way than checking if `--projectPath` was not set explicitly AND `--modulePath` is absolute.

I personally would prefer the first solution and force the use of the `--no-project` flag since this is potentially the more seldom use case anyways. And it can't accidentally go wrong due to executing the command in the wrong directory or giving a path as relative instead of absolute. Also this doesn't change the current behavior.

**Comment by RalfEggert** [comment]
Did a lot of refactoring now to handle module creation within or without a ZF2 project.

https://github.com/ZFrapid/zf2rapid/commit/e1743a1bc63797de8188a1834298f698a6a51023

If you want to create a module within a ZF2 project you can simply call this command. This will check for a ZF2 project within the current working path.

```
$ zf2rapid create-module Shop
```

If you want to create a module for a ZF2 project which is not located in the current working path you can call this command. This will check for a ZF2 project within the given working path.

```
$ zf2rapid create-module Shop --workingPath=/path/to/zf2-project
```

If you want to create a module outside of any ZF2 project you need to specify the `workingPath` and add the `without-project` flag. In this case no activation and class map / template map generation will be run:

```
$ zf2rapid create-module Shop --workingPath=/path/to/anywhere --without-project
```

Please check if you can work with this solution and close issue if so.

**Comment by hoppithek** [comment]
\o/ fantastic. Just tried out module creation `--without-project` and it works like a charm. Didn't dig too deep in the other options, but I assume they work just as smoothly. I wasn't sure at first what would happen.

If I supply a Project Path the new module will be created in the module subfolder (actually I didn't test that, but seems reasonable). When I use --without-project no subfolder structure is assumed. I think this is the desired behavior. Maybe the explanation could be a little more clear about it

    Ignore if working path does not contain a ZF2 project; defaults to current working path

    Creates the module directly in the working path. Without checking for and integration into a project.

Something along those lines. Great work. Thanks.

**Comment by RalfEggert** [comment]
Thanks for your feedback. I will add the `--without-project` flag to the docs
