### ISSUE TITLE
Command line choices prevent batch creation

### ISSUE THREAD

**Issue by mike-a** [ZFrapid/zf2rapid#12]
At v0.6, console commands like "zf2rapid create-module Shop" provide human entry choices. For example, module creation provides a choice between development and production config. This seems to prevent forming batch files for bulk creation: non-human input is difficult at batch level.

Requiring a command line filename parameter instead of a command line choice would enable building several module skeletons in one go. Is this something to be considered?

I used Windows 7 for my tests.

**Comment by RalfEggert** [comment]
Currently, when creating a module the `/config` path of the project is scanned for all `*.config.php` files and a list of all available config files is shown to collect one of them. The config files are ordered alphabetically and marked with an char. It could look like this:

```
[ PICK] Which configuration file should be updated to activate the module?
       a) development.config.php
       b) production.config.php
       c) testing.config.php
```

If we add a filename parameter we could either ask for this char or for the full filename. Maybe like this

```
$ zf2rapid create-module Shop --configFile=development.config.php
```

Or for just activating a module:

```
$ zf2rapid activate-module Shop --configFile=production.config.php
```

What that make sense to you?

**Comment by mike-a** [comment]
Yes, perfect! This way a batch file in any operating system can add the filename parameter. Developers can therefore add many modules/controllers/actions at the same time.

**Comment by RalfEggert** [comment]
It was much easier to implement than I thought. But here you go:

https://github.com/ZFrapid/zf2rapid/commit/d5e7eebe9a9d6fe1202ef7e756f327c7ebb437a5

Please test it. I will close the issue. Please reopen it, if you encounter any problems.
