### ISSUE TITLE
Implement an optional flag to prevent zf2rapid from editing module.config.php

### ISSUE THREAD

**Issue by Koopzington** [ZFrapid/zf2rapid#13]
Just as there's an option to turn off the automatic activation of a module, I'd like to see an option to turn off the adding of generated classes to the module.config.php *cough* and also converting my short array syntax to the traditional one and replacing my Foobar::class usages with 'Foobar' *cough*

;)

**Comment by hoppithek** [comment]
+1
prevent changes in configs would be a great option.

**Comment by RalfEggert** [comment]
Well, one important feature of ZF2rapid is the module configuration part. But, if you want this, you will get it... ;-)

Won't be such a big deal.

**Comment by RalfEggert** [comment]
Solved
