### ISSUE TITLE
Usage of ServiceLocatorAwareInterface correct?

### ISSUE THREAD

**Issue by Koopzington** [ZFrapid/zf2rapid#15]
I'm not sure but wouldn't it make more sense to use the ServiceLocatorInterface in the PhpDoc block since you set the main ServiceManager as $serviceLocator in the line under it?
[ZF2rapid/Generator/FactoryGenerator](https://github.com/ZFrapid/zf2rapid/blob/0.6.2/src/ZF2rapid/Generator/FactoryGenerator.php#L94)

**Comment by RalfEggert** [comment]
Need to think about this one.

**Comment by RalfEggert** [comment]
fixed it
