### ISSUE TITLE
ConfigFileGenerator converts all ")" to "]" 

### ISSUE THREAD

**Issue by RalfEggert** [ZFrapid/zf2rapid#18]
The `ZF2rapid\Generator\ConfigFileGenerator` converts all ")" to "]". The aim is to convert the old array-syntax to the new short syntax. But since all ")" are converted these leads to bugs for example in the routing configuration on strict mode:

```
'action' => '(index|show]',
```

https://github.com/ZFrapid/zf2rapid/blob/master/src/ZF2rapid/Generator/ConfigFileGenerator.php#L36

**Comment by fiesagit** [comment]
Sorry, that i forgot to set a friendly reminder for you. But fortunately, you seem less forgetfull than me. :)

**Comment by RalfEggert** [comment]
@fiesagit ;-)

**Comment by RalfEggert** [comment]
To clarify this- The mentioned code line above was just a quick hack since the `Zend\Code\Generator\ValueGenerator` cannot handle the array short syntax (see https://github.com/zendframework/zend-code/issues/9).

The proper fix for this issue would be a fix to `Zend\Code\Generator\ValueGenerator`.

**Comment by RalfEggert** [comment]
Added a pull request to `Zend\Code`. Now we need to wait for it to be accepted and a new release to be published.

https://github.com/zendframework/zend-code/pull/12

**Comment by RalfEggert** [comment]
Since the `Zend\Code` PR was merged already this issue can be closed now.
