### ISSUE TITLE
Standardize usage of parameters inside the CLI commands

### ISSUE THREAD

**Issue by RalfEggert** [ZFrapid/zf2rapid#2]
Based on a discussion with @manuakasam on Facebook the usage of parameters should be standardized inside the CLI commands and should match the real world scenarios as best as possible. For example, when creating a new controller an additional factory should always be created and not optionally. To prevent the creation of the controller, he suggest to use very verbose parameters like this:

```
zf2rapid create-controller <module> <controller> [<path>] [--no-factory]
zf2rapid create-controller <module> <controller> [<path>] [--type=invokable|factory]
zf2rapid create-controller <module> <controller> [<path>] [--as-invokable|--as-factory]
```

For factories, I would prefer the ```--no-factory``` param, since its the simplest and easiest to understand. 

Currently, there is only one other flag used, when creating routing:

```
zf2rapid create-routing <module> [<path>] [--strict|-s]:strict
```

That could be changed to this:

```
zf2rapid create-routing <module> [<path>] [--strict-routing]
```

When the ```--strict-routing``` is not used, the unstrict routing will be created.

Thoughts and ideas?

**Comment by manuakasam** [comment]
:+1: --no-factory

For the other one, what is strict/unstrict routing?

**Comment by RalfEggert** [comment]
Strict Routing only allows existing controllers and actions, while unstrict routing uses constraints like ```[a-zA-Z][a-zA-Z0-9_-]*```

https://github.com/ZFrapid/zf2rapid/blob/master/docs/tutorial-create-routing-maps.md#create-routing

**Comment by manuakasam** [comment]
Alright, makes sense. Was kind of looking for a more verbose naming for this parameter but I can't come up with anything myself, so I suppose strict is a good option. Thus:

:+1:  `--strict`
