### ISSUE TITLE
Lean factories

### ISSUE THREAD

**Issue by werc** [ZFrapid/zf2rapid#21]
Factories can be build with **__invoke** method, so the *use* and *implement* can be reduced.
Example:
```php
<?php
namespace Concerts\Controller\Factory;

use Concerts\Controller\ConcertsController;

class ConcertsControllerFactory
{

    public function __invoke($serviceLocator)
    {
        $services = $serviceLocator->getServiceLocator();
        $serviceConcerts = $services->get('Concerts\Service\Concerts');
        
        return new ConcertsController($serviceConcerts);
    }
}
```
More in A. Celaya blog http://blog.alejandrocelaya.com/2014/10/09/advanced-usage-of-service-manager-in-zend-framework-2/

**Comment by RalfEggert** [comment]
Good point. Need to refactor that when I find the time...

**Comment by RalfEggert** [comment]
Currently, I will leave the factories as is for the ZF2rapid tool. But soon I will start working on ZF3rapid which will create other and simpler factories. So, this will be fixed but in a soon to come other repository.
