### ISSUE TITLE
show-modules: Directories in config-directory gives warnings

### ISSUE THREAD

**Issue by gartner** [ZFrapid/zf2rapid#22]
When running
zf2rapid show-modules

in a project that has a directory in the config/-folder, I get warnings that the file cannot be included:

PHP Warning:  include(/home/mads/hosts/test.rakkeby-planteskole.dk/config/DB_schemas): failed to open stream: Success in /home/mads/code/zf2rapid/src/ZF2rapid/Task/Fetch/LoadModules.php on line 151
PHP Warning:  include(): Failed opening '/home/mads/hosts/test.rakkeby-planteskole.dk/config/DB_schemas' for inclusion (include_path='.:/usr/share/php7:/usr/share/php7/PEAR') in /home/mads/code/zf2rapid/src/ZF2rapid/Task/Fetch/LoadModules.php on line 151

I can see that Task\Fetch\LoadModules will filter out the 'autoload' directory, but no other checks are done.

The code still completes as it is supposed to, it just show these warnings when the error-level of php is set to show warnings.

**Comment by RalfEggert** [comment]
I fixed the issue. Soon I will create a new release. Thanks for reporting!
