### ISSUE TITLE
Hydratorfactories adds strategies wrong

### ISSUE THREAD

**Issue by gartner** [ZFrapid/zf2rapid#25]
Hi

Running 'zf2rapid crud-create-model', if the tables has foreign keys, strategies are added to the Hydrators returned form the <tablename>HydratorFactory.

Strategies are added like this:

```$instance->addStrategy('tbl_menu', new TblMenuStrategy());```

- where 'tbl_menu' is the name of the foreign table. 
It should instead use the fieldname containing the foreign key.

```$instance->addStrategy('menu_id', new TblMenuStrategy());```

An example: 
run
´´´zf2rapid crud-create-model tbl_pages,tbl_menus´´´

Tbl_pages looks like:
id,
content,
menu_id // This holds the foreign key to tbl_menus

An entity will be generated for Tbl_pages with a setter for menu_id that looks like:
´´´protected function setMenuId(TblMenuEntity $menuId)```

But when this is hydrated, it will call setMenuId() with the integer value of the field menu_id.
- the strategy is not being used for this field.

**Comment by RalfEggert** [comment]
Merged your PR
