### ISSUE TITLE
Fatal errors when using zend-eventmanager >3.0

### ISSUE THREAD

**Issue by Koopzington** [ZFrapid/zf2rapid#30]
https://zendframework.github.io/zend-eventmanager/migration/removed/

Since EventManagerInterface::setSharedManager() got removed, zf2rapid is throwing fatal errors when trying to list controllers or creating routing (maybe more, just tried these 2 commands).

**Comment by RalfEggert** [comment]
This was fixed yesterday. I will create a new release soon than you can check it.
