### ISSUE TITLE
completion script

### ISSUE THREAD

**Issue by basz** [ZFrapid/zf2rapid#7]
Output of `zf2rapid.php autocomplete` output contains a ansi colored header & footer which messes up the script.

This won't work then;
```
# The easiest way will be to run
#
# $ sudo /Users/bas/.composer/vendor/bin/zf2rapid.php autocomplete > /etc/bash_completion.d/zf2rapid.php.sh
# $ source /etc/bash_completion.d/zf2rapid.php.sh
```

**Comment by RalfEggert** [comment]
You are right. I need to overwrite the standard autocomplete command from ZF\Console to fix this and do a little refactoring how and when to output the banner and footer.

**Comment by RalfEggert** [comment]
I implemented a work around. The better solution would be to fix `ZF\Console` to have more flexible commands.
