### ISSUE TITLE
Do not overwrite application.config.php

### ISSUE THREAD

**Issue by hoppithek** [ZFrapid/zf2rapid#9]
Overwriting the `application.config.php` is not always a wanted behavior.
- deletes comments
- reformats the code
- adds module paths that might be already added in different ways

A better way might be to just put all the zf2rapid configuration into `<APP_ROOT> . '/config/global/zf2rapid.global.php'`.  Good enough for complete zf2rapid usage and way easier to merge for those that want to retain their own `application.config.php`

The inclusion of `<APP_ROOT> . '/config/global/*global.php' is already part of the skeleton application.

**Comment by RalfEggert** [comment]
Please advise where the skeleton application is using any config files from the path `/config/global/`. I was only aware of the config files within `/config/autoload/` path which are NOT merged with the config data from `/config/application.config.php`. 

Anyway, please note that ZF2rapid has a strong focus on ZF2 beginners. Deleting comments and reformatting code shouldn't be such a big deal. I am not sure what you mean with 'module paths that might be already added in different ways'. 

Please clarify! Thanks

**Comment by hoppithek** [comment]
I mixed things up in the excitement of having a working code generator for ZF2. config/global should totally be `config/autoload`.

Aside from adding the module being modified by zf2rapid to the modules array in application.config.php I didn't see any changes in my application.config, though to be honest I didn't test very long. I still think rewriting the complete config does more harm than good. It looks like the config is evaluated changed and than saved back to file. This removes any programmatic content and you are left with what you had, while zf2rapid was running. Most of the time this instantly breaks portability of the application, to a different server or even a different path.

In my case I reverted the configs and added any needed changes myself by hand. Actually making the changes in the file and not touching anything that doesn't need touching would be the ideal way, but that is probably asking too much. I don't expect a code generator to completely understand exiting code. Mine for example contained calls to `getenv` and relied on constants set in `index.php`, but the environment of zf2rapid differs from the one the application is usually run in.

Since doing the changes inline seemed a bit complex I thought that a different approach would suit both better. A beginner might not even notice the changes in the application.config.php. Things just magically work or the app is magically broken. To solve this I was thinking along the lines of putting the zf2rapid code in one location and not touching existing code. Kinda link

File application.config.php:

    {
      $config = include original.application.config.php
      return applyZf2RapidChangesTo($config);

      function applyZf2RapidChangesTo($config)
      {
        // do all zf2rapid changes here, so ppl can see them and
        // merge them into original.application.config.php by hand
        return $config;
      }
    }

I don't want to raise hell by overloading the application.config.php with anything else than a config array, but that was the first approach that came to mind, on how you could leave the original application.config.php untouched while keeping the zf2rapid changed in one place for documentation and still have all the changes directly visible in the running application.

For any other changes to configs, e.g. module configs I would like it better to see all changed documented in a zf2rapid.global.php in config/autoload. You can overwrite any existing module config if you need to or just add what changes you need. Probably just some registering in some service provider. You could even spit it into multiple files to keep changes for each module in one file.

Both approaches would 
 * leave you with working configs
 * keep the original untouched
 * remove the extra effort of parsing the configs in a way that they can be reconstructed as close as possible to the original (like keeping some constants  unevaluated)
 * make it crystal clear what changes zf2rapid does to the configs (I think this would help beginners more to understand what is going on than a ready made config without comments or hints of what was actually changed)
 * probably would make deletion a lot harder since orignial configs are considered untouchable in this approach

there are probably a hundred reasons more why this is a good or bad idea, but I hope you got a better understanding of what I was trying to say/suggest.

**Comment by RalfEggert** [comment]
To be honest, I think it is a really bad practice when configuration files contain logic or even methods. And I think that it will be quite hard that ZF2rapid could handle such a specific use case you have mentioned. 

The whole idea of ZF2rapid is to help beginners to start their ZF2 projects by providing some help to build the basic parts of new applications and modules. This means, that overwriting the configuration files is quite essential. 

But I don't want to leave you out in the rain. So here are some suggestions.

1. You should move the config logic from your `config/application.config.php` to your `public/index.php` file. I think it is no problem to add more logic there. Look at the [ZF2rapid SkeletonApplication](https://github.com/ZFrapid/zf2rapid-skeleton/blob/master/public/index.php) for an example how to handle such a scenario.

2. I could add a `--no-activation` flag to the `create-module` command. Then your `config/application.config.php` will not be changed when creating a module. And the `delete-module' command could get a `--no-activation` flag to keep the `config/application.config.php` unchanged.

Would that help you?

**Comment by hoppithek** [comment]
I totally agree that it would be bad practice to put anything else into a config file than the config. You are absolutely right that, if one wants to generate the application config dynamically the index.php is a better place than the config file itself. 

Not doing any changes to the `application.config.php`, or any other config would also suit me. Maybe a `--no-config-changes` switch would be best. Ideally with output to the console, what needs to be chaged in the configs. Like `ensure application.config.php contains config key ['modules' => ['newModuleName']]`.

Could also be interactive. Ask the user `config key ['modules' => ['newModuleName']] needs to be added to application.config.php. Do this automatically? [y|n]` or `module config change in path/to/module.config.php required: key x => y => z needs to be added, key a => b => c needs to be removed, ...' Apply these changes automatically now? [y|n]`.

Thanks for looking into this.

**Comment by RalfEggert** [comment]
Well, I am trying to use self-explaining flags like `--no-activation` and make the usage for beginners as easy as possible. The default behaviour is now, that the config files are change and the module is activated. If you don't want it you can turn it off now.

See also [the Command-Guide](https://github.com/ZFrapid/zf2rapid/blob/master/docs/command-guide.md#modules)

**Comment by hoppithek** [comment]
Great! Thanks.
